#! /bin/bash

help() {
    echo "missing argument"
    echo "example: createpy [--package,-p] <package_name>"
    echo "example: createpy [--module,-m] <module_name>"
    exit 1
}

make_package(){
    mkdir $1
    cd $1
    touch __init__.py
    echo \"\"\"$1 package.\"\"\" >> __init__.py
}

make_module(){
    touch $1.py
    echo \"\"\"$1 module.\"\"\" >> $1.py
}

if [[ $# -eq 0 ]]; then
    help
fi

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    -m|--module)
      [[ $# -ge 2 ]] || { echo "Error: $1 requires a value" >&2; help; }
      module="$2"
      make_module $module
      shift 2
      ;;
    -p|--package)
      [[ $# -ge 2 ]] || { echo "Error: $1 requires a value" >&2; help; }
      package="$2"
      make_package $package
      shift 2
      ;;
    -h|--help)
      help 
      ;;
    --) # end of options
      shift
      break
      ;;
    -*)
      echo "Error: unknown option: $1" >&2
      usage
      ;;
    *)
      break
      ;;
  esac
done
